# Generated by Django 3.0.7 on 2020-08-13 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yazilar', '0002_auto_20200717_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yazi',
            name='yazar',
        ),
        migrations.AddField(
            model_name='yazi',
            name='konu',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
