# Generated by Django 3.0.7 on 2020-08-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yazilar', '0004_auto_20200814_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='konu',
            field=models.CharField(default='', max_length=50),
        ),
    ]
