# Generated by Django 3.0.7 on 2020-08-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yazilar', '0005_auto_20200814_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='konu',
            field=models.CharField(default='konu', max_length=50),
        ),
    ]
