# Generated by Django 3.0.7 on 2020-08-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yazilar', '0006_auto_20200814_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yazi',
            name='konu',
        ),
        migrations.AddField(
            model_name='yazi',
            name='başlık',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
