# Generated by Django 3.0.7 on 2020-08-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yazilar', '0009_auto_20200814_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yazi',
            name='başlık',
            field=models.CharField(default='', max_length=50),
        ),
    ]
